### ISSUE TITLE
Remove possibility of specification of prefix

### ISSUE THREAD

**Issue by 1D0BE** [MEH-Design/atomicms#24]
It is to inconvenient to give the developer the non-neccessary possibility to configure a prefix himself. 
Make it hardcoded.

**Comment by MiniXC** [comment]
we could entirely ditch the ``attributes`` attribute in ``opts``.

**Comment by bminixhofer** [comment]
i removed the `prefix` attribute for now. As we discussed, at least `content` could be useful, so we should leave the rest as they are for now.
